### ISSUE TITLE
why no 'View text/logs/html online' action after my installation ?

### ISSUE THREAD

**Issue by youcanwin2088** [guuuuo/sfe4j#9]
Why no 'View text/logs/html online' action after my installation ?
Also there isn't any clue onf your demo:https://sfe4j-demo.amoylabs.com:30443/file-explorer?dir=/usr/share/i18n/locales/musl !
There is only 'download'!

**Comment by guuuuo** [comment]
Hi @youcanwin2088, only text/logs/html files can be viewed online currently. Can test it by clicking the file name `app.log` at https://sfe4j-demo.amoylabs.com:30443/file-explorer?dir=/data/logs, or can access https://sfe4j-demo.amoylabs.com:30443/file-viewer?file=/data/logs/app.log to view `/data/logs/app.log` directly.

**Comment by youcanwin2088** [comment]
Got it! I just explored those files which are not txt/log/html  ! :(
